# Generated by Django 5.2 on 2025-12-30 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Login_Info',
            fields=[
                ('admin_name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('admin_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('date', models.DateField()),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(editable=False, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.admin_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Info',
            fields=[
                ('employee_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='홍길동', max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('mobile_carrier', models.CharField(max_length=20)),
                ('resident_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee_number',), name='unique_employee_number'), models.UniqueConstraint(fields=('user_id',), name='unique_user_id'), models.UniqueConstraint(fields=('resident_number',), name='unique_resident_number'), models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number')],
            },
        ),
        migrations.CreateModel(
            name='User_Work_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('daily_wages', models.IntegerField()),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('work_date', models.DateField()),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
                ('work_place', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=20)),
                ('minutes', models.PositiveIntegerField()),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info')),
                ('work_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.user_workday')),
            ],
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(editable=False, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.user_login_info')),
            ],
        ),
    ]
