# Generated by Django 5.1.7 on 2026-01-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_workdetail",
            name="employee_number",
        ),
    ]
