# Generated by Django 5.1.7 on 2026-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_user_workdetail_employee_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_workdetail",
            name="employee_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
