# Generated by Django 5.2 on 2026-01-27 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_workdetail_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login_info',
            name='admin_uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='user_login_info',
            name='user_uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user_login_info',
            name='user_id',
            field=models.CharField(null=True, editable=False),
        ),
    ]
