# Generated by Django 5.2 on 2026-01-27 19:55
import uuid
from django.db import migrations

def fill_uuid(apps, schema_editor):
    User = apps.get_model("myapp", "User_Login_Info")
    for u in User.objects.filter(user_uuid__isnull=True).iterator():
        u.user_uuid = uuid.uuid4()
        u.save(update_fields=["user_uuid"])

class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_admin_login_info_admin_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_uuid, migrations.RunPython.noop),
    ]
