# Generated by Django 5.2 on 2026-01-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_admin_login_info_admin_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrefreshtoken',
            name='admin_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.admin_login_info', to_field='admin_uuid'),
        ),
        migrations.AddField(
            model_name='user_work_pay',
            name='user_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_pays', to='myapp.user_login_info', to_field='user_uuid'),
        ),
        migrations.AddField(
            model_name='user_workday',
            name='user_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='myapp.user_login_info', to_field='user_uuid'),
        ),
        migrations.AddField(
            model_name='userrefreshtoken',
            name='user_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.user_login_info', to_field='user_uuid'),
        ),
        migrations.AlterField(
            model_name='adminrefreshtoken',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens_by_old', to='myapp.admin_login_info'),
        ),
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens_by_emp', to='myapp.user_login_info'),
        ),
    ]
