# Generated by Django 5.2 on 2026-01-27 20:35

from django.db import migrations




def forwards(apps, schema_editor):
    UserWorkDay = apps.get_model("myapp", "User_WorkDay")
    UserWorkPay = apps.get_model("myapp", "User_Work_Pay")
    UserToken   = apps.get_model("myapp", "UserRefreshToken")
    AdminToken  = apps.get_model("myapp", "AdminRefreshToken")

    # 1) User_WorkDay.user_uuid 채우기 (기존 employee_number FK -> user_uuid)
    for wd in UserWorkDay.objects.select_related("employee_number").all().iterator():
        if wd.user_uuid_id is None and wd.employee_number_id is not None:
            wd.user_uuid_id = wd.employee_number.user_uuid
            wd.save(update_fields=["user_uuid"])

    # 2) User_Work_Pay.user_uuid 채우기 (기존 employee_number FK -> user_uuid)
    for wp in UserWorkPay.objects.select_related("employee_number").all().iterator():
        if wp.user_uuid_id is None and wp.employee_number_id is not None:
            wp.user_uuid_id = wp.employee_number.user_uuid
            wp.save(update_fields=["user_uuid"])

    # 3) UserRefreshToken.user_uuid 채우기 (기존 user FK -> user_uuid)
    #    0007에서 user 필드는 그대로 있고(user_id), user_uuid FK가 추가됨
    for t in UserToken.objects.select_related("user").all().iterator():
        if t.user_uuid_id is None and t.user_id is not None:
            t.user_uuid_id = t.user.user_uuid
            t.save(update_fields=["user_uuid"])

    # 4) AdminRefreshToken.admin_uuid 채우기 (기존 admin FK -> admin_uuid)
    for t in AdminToken.objects.select_related("admin").all().iterator():
        if t.admin_uuid_id is None and t.admin_id is not None:
            t.admin_uuid_id = t.admin.admin_uuid
            t.save(update_fields=["admin_uuid"])


def backwards(apps, schema_editor):
    UserWorkDay = apps.get_model("myapp", "User_WorkDay")
    UserWorkPay = apps.get_model("myapp", "User_Work_Pay")
    UserToken   = apps.get_model("myapp", "UserRefreshToken")
    AdminToken  = apps.get_model("myapp", "AdminRefreshToken")

    UserWorkDay.objects.update(user_uuid=None)
    UserWorkPay.objects.update(user_uuid=None)
    UserToken.objects.update(user_uuid=None)
    AdminToken.objects.update(admin_uuid=None)


class Migration(migrations.Migration):

    dependencies = [
        # ✅ 여기 줄은 makemigrations가 자동으로 채워준 값 "그대로" 두기
        # 예: ("myapp", "0007_auto_20260127_2025") 처럼 자동 입력된 실제 0007 이름
        ("myapp", "0007_adminrefreshtoken_admin_uuid_user_work_pay_user_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
