# Generated by Django 5.2 on 2026-01-27 21:00

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_remove_adminrefreshtoken_admin_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
            -- 1) user_uuid NULL 있으면 안 됨
            UPDATE myapp_user_login_info
            SET user_uuid = gen_random_uuid()
            WHERE user_uuid IS NULL;

            -- 2) 중복 제거(혹시라도) - 중복 있으면 여기서 에러날 수 있음
            -- (중복이 있다면 먼저 데이터를 정리해야 함)

            -- 3) 기존 PK(employee_number) 제거
            ALTER TABLE myapp_user_login_info
            DROP CONSTRAINT myapp_user_login_info_pkey;

            -- 4) user_uuid를 PK로 설정
            ALTER TABLE myapp_user_login_info
            ADD CONSTRAINT myapp_user_login_info_pkey PRIMARY KEY (user_uuid);

            -- 5) employee_number는 UNIQUE로 남김(원하면 유지)
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'myapp_user_login_info_employee_number_key'
              ) THEN
                ALTER TABLE myapp_user_login_info
                ADD CONSTRAINT myapp_user_login_info_employee_number_key UNIQUE (employee_number);
              END IF;
            END$$;
            """,
            reverse_sql=r"""
            ALTER TABLE myapp_user_login_info
            DROP CONSTRAINT myapp_user_login_info_pkey;

            ALTER TABLE myapp_user_login_info
            ADD CONSTRAINT myapp_user_login_info_pkey PRIMARY KEY (employee_number);
            """,
        ),
    ]
