# Generated by Django 5.2 on 2026-01-27 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010b_fill_admin_uuid"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
            -- 0) adminrefreshtoken -> admin_login_info(admin_uuid) FK 먼저 제거
            DO $$
            DECLARE
              fk_name text;
            BEGIN
              SELECT conname INTO fk_name
              FROM pg_constraint
              WHERE conrelid = 'myapp_adminrefreshtoken'::regclass
                AND contype = 'f'
                AND conname LIKE '%admin_uuid%';

              IF fk_name IS NOT NULL THEN
                EXECUTE format('ALTER TABLE myapp_adminrefreshtoken DROP CONSTRAINT %I', fk_name);
              END IF;
            END$$;

            -- 1) Admin_Login_Info PK를 admin_uuid로 변경
            -- (기존 PK는 id였을 가능성이 큼)
            ALTER TABLE myapp_admin_login_info
            DROP CONSTRAINT myapp_admin_login_info_pkey;

            ALTER TABLE myapp_admin_login_info
            ADD CONSTRAINT myapp_admin_login_info_pkey PRIMARY KEY (admin_uuid);

            -- 2) admin_id는 UNIQUE 유지(없으면 생성)
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'myapp_admin_login_info_admin_id_key'
              ) THEN
                ALTER TABLE myapp_admin_login_info
                ADD CONSTRAINT myapp_admin_login_info_admin_id_key UNIQUE (admin_id);
              END IF;
            END$$;

            -- 3) FK 다시 생성 (adminrefreshtoken.admin_uuid_id -> admin_login_info.admin_uuid)
            ALTER TABLE myapp_adminrefreshtoken
            ADD CONSTRAINT myapp_adminrefreshtoken_admin_uuid_id_fk
            FOREIGN KEY (admin_uuid_id)
            REFERENCES myapp_admin_login_info (admin_uuid)
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=r"""
            -- 롤백은 필요하면 작성 (보통 생략)
            """,
        )
    ]
