# Generated by Django 5.2 on 2026-01-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_admin_login_info_admin_id_and_more'),
    ]

    operations = [
        # employee_number unique constraint가 DB에 없을 수도 있으니 안전하게
        migrations.RunSQL(
            sql=r"""
            ALTER TABLE myapp_user_login_info
            DROP CONSTRAINT IF EXISTS unique_employee_number;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # employee_number 컬럼 삭제
        migrations.RunSQL(
            sql=r"""
            ALTER TABLE myapp_user_login_info
            DROP COLUMN IF EXISTS employee_number;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]