# Generated by Django 5.2 on 2025-07-27 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_Info',
            new_name='User_Work_Info',
        ),
        migrations.RenameModel(
            old_name='Work_Pay',
            new_name='User_Work_Pay',
        ),
    ]
