# Generated by Django 5.2 on 2026-01-31 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_user_login_info_unique_employee_number_and_more'),
    ]

    operations = [
        # ==============================
        # 1) user_login_info 제약/컬럼: 없을 수도 있으니 IF EXISTS로 방어
        # ==============================

        # ----- constraint: unique_employee_number -----
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "myapp_user_login_info" DROP CONSTRAINT IF EXISTS "unique_employee_number";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='user_login_info',
                    name='unique_employee_number',
                ),
            ],
        ),

        # ----- constraint: unique_user_id -----
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "myapp_user_login_info" DROP CONSTRAINT IF EXISTS "unique_user_id";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='user_login_info',
                    name='unique_user_id',
                ),
            ],
        ),

        # ----- column: user_login_info.employee_number -----
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "myapp_user_login_info" DROP COLUMN IF EXISTS "employee_number";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='user_login_info',
                    name='employee_number',
                ),
            ],
        ),

        # ----- column: user_workdetail.employee_number -----
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "myapp_user_workdetail" DROP COLUMN IF EXISTS "employee_number";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='user_workdetail',
                    name='employee_number',
                ),
            ],
        ),

        # ==============================
        # 2) admin_uuid PK 전환: FK 떼고 → PK 전환 → FK 다시 붙이기
        # ==============================

        migrations.AlterField(
            model_name='admin_login_info',
            name='admin_id',
            field=models.CharField(max_length=50, unique=True),
        ),

        # ✅ admin_uuid를 PK로 바꾸기 전에 FK 제약을 먼저 제거
        migrations.RunSQL(
            sql='''
            ALTER TABLE "myapp_adminrefreshtoken"
            DROP CONSTRAINT IF EXISTS "myapp_adminrefreshtoken_admin_uuid_id_fk";
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='admin_login_info',
            name='admin_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # ✅ PK 전환 후 FK 다시 생성
        migrations.RunSQL(
            sql='''
            ALTER TABLE "myapp_adminrefreshtoken"
            ADD CONSTRAINT "myapp_adminrefreshtoken_admin_uuid_id_fk"
            FOREIGN KEY ("admin_uuid_id")
            REFERENCES "myapp_admin_login_info" ("admin_uuid")
            DEFERRABLE INITIALLY DEFERRED;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='adminrefreshtoken',
            name='admin_uuid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='refresh_tokens',
                to='myapp.admin_login_info',
            ),
        ),

        # ==============================
        # 3) user_uuid PK 전환 관련: FK 3개 떼고 → (state만 PK 처리) → FK 3개 다시 붙이기
        # ==============================

        # ✅ user_uuid PK 전환 전, 의존하는 FK 3개 제거
        migrations.RunSQL(
            sql='''
            ALTER TABLE "myapp_user_work_pay"
            DROP CONSTRAINT IF EXISTS "myapp_user_work_pay_user_uuid_id_732daefb_fk_myapp_use";

            ALTER TABLE "myapp_user_workday"
            DROP CONSTRAINT IF EXISTS "myapp_user_workday_user_uuid_id_7166774a_fk_myapp_use";

            ALTER TABLE "myapp_userrefreshtoken"
            DROP CONSTRAINT IF EXISTS "myapp_userrefreshtok_user_uuid_id_aa965828_fk_myapp_use";
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ✅ 여기 핵심: DB는 건드리지 않고(state만 user_uuid를 PK로)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='user_login_info',
                    name='user_uuid',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),

        # ✅ FK 3개 다시 생성 (DB 기준 user_uuid 참조)
        migrations.RunSQL(
            sql='''
            ALTER TABLE "myapp_user_work_pay"
            ADD CONSTRAINT "myapp_user_work_pay_user_uuid_id_732daefb_fk_myapp_use"
            FOREIGN KEY ("user_uuid_id")
            REFERENCES "myapp_user_login_info" ("user_uuid")
            DEFERRABLE INITIALLY DEFERRED;

            ALTER TABLE "myapp_user_workday"
            ADD CONSTRAINT "myapp_user_workday_user_uuid_id_7166774a_fk_myapp_use"
            FOREIGN KEY ("user_uuid_id")
            REFERENCES "myapp_user_login_info" ("user_uuid")
            DEFERRABLE INITIALLY DEFERRED;

            ALTER TABLE "myapp_userrefreshtoken"
            ADD CONSTRAINT "myapp_userrefreshtok_user_uuid_id_aa965828_fk_myapp_use"
            FOREIGN KEY ("user_uuid_id")
            REFERENCES "myapp_user_login_info" ("user_uuid")
            DEFERRABLE INITIALLY DEFERRED;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='user_work_pay',
            name='user_uuid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='work_pays',
                to='myapp.user_login_info',
            ),
        ),
        migrations.AlterField(
            model_name='user_workday',
            name='user_uuid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workdays',
                to='myapp.user_login_info',
            ),
        ),
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user_uuid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='refresh_tokens',
                to='myapp.user_login_info',
            ),
        ),
    ]
