# Generated by Django 5.2 on 2025-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_work_info_user_work_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('food_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etc_expense', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('revenue_date', models.DateField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
