# Generated by Django 5.2 on 2026-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_user_login_info_unique_employee_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workdetail',
            name='user_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
