# Generated by Django 5.2 on 2025-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_expenseinfo_revenueinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenseInfo',
        ),
        migrations.DeleteModel(
            name='RevenueInfo',
        ),
        migrations.RemoveField(
            model_name='admin_login_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin_login_info',
            name='admin_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
