# Generated by Django 5.2 on 2026-02-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_workdetail_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workdetail',
            name='user_uuid',
            field=models.UUIDField(),
        ),
    ]
