# Generated by Django 5.2 on 2025-09-21 18:06

from django.db import migrations, models
import random

def generate_unique_serial(model_class):
    while True:
        number = random.randint(100000, 999999)
        if not model_class.objects.filter(serial_number=number).exists():
            return number

def populate_serial_numbers(apps, schema_editor):
    Expense = apps.get_model('myapp', 'Expense')
    Income = apps.get_model('myapp', 'Income')

    for expense in Expense.objects.filter(serial_number__isnull=True):
        expense.serial_number = generate_unique_serial(Expense)
        expense.save()

    for income in Income.objects.filter(serial_number__isnull=True):
        income.serial_number = generate_unique_serial(Income)
        income.save()

class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0015_expense_income_delete_expenseinfo_delete_revenueinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='serial_number',
            field=models.IntegerField(primary_key=True, editable=False),
        ),
        migrations.AddField(
            model_name='income',
            name='serial_number',
            field=models.IntegerField(primary_key=True, editable=False),
        ),
        migrations.RunPython(populate_serial_numbers),
    ]