# Generated by Django 5.2 on 2025-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_expense_income_delete_expenseinfo_delete_revenueinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='serial_number',
            field=models.IntegerField(default=123456, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='serial_number',
            field=models.IntegerField(default=123456, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
