# Generated by Django 5.2 on 2025-09-24 13:17

from django.db import migrations, models


def populate_serial_numbers(apps, schema_editor):
    Expense = apps.get_model('myapp', 'Expense')
    Income = apps.get_model('myapp', 'Income')

    # Expense 기존 데이터 채우기
    max_sn_expense = Expense.objects.aggregate(models.Max('serial_number'))['serial_number__max'] or 0
    for i, obj in enumerate(Expense.objects.filter(serial_number__isnull=True), start=1):
        obj.serial_number = max_sn_expense + i
        obj.save()

    # Income 기존 데이터 채우기
    max_sn_income = Income.objects.aggregate(models.Max('serial_number'))['serial_number__max'] or 0
    for i, obj in enumerate(Income.objects.filter(serial_number__isnull=True), start=1):
        obj.serial_number = max_sn_income + i
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_expense_income_delete_expenseinfo_delete_revenueinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='serial_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='income',
            name='serial_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
