# Generated by Django 5.2 on 2026-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_user_workdetail_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workday',
            name='work_shift',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='user_workday',
            constraint=models.UniqueConstraint(fields=('user_uuid', 'work_date', 'work_shift'), name='uniq_user_date_shift'),
        ),
    ]
