# Generated by Django 5.2 on 2025-09-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_expense_serial_number_income_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AlterField(
            model_name='expense',
            name='serial_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='serial_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
