# Generated by Django 5.2 on 2026-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_workday_work_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workday',
            name='work_shift',
            field=models.CharField(default='주간', max_length=2),
            preserve_default=False,
        ),
    ]
