# Generated by Django 5.2 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_expense_id_remove_income_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='income',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='serial_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
