# Generated by Django 5.2 on 2026-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_user_workday_work_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_workdetail',
            name='is_overtime_approved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
