# Generated by Django 5.2.7 on 2025-10-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_adminrefreshtoken_userrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user',
            field=models.ForeignKey(db_column='employee_number', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.user_login_info'),
        ),
    ]
