# Generated by Django 5.2 on 2026-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_workdetail_is_overtime_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_workdetail',
            name='is_overtime_approved',
            field=models.BooleanField(default=False),
        ),
    ]
