# Generated by Django 5.2 on 2025-11-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_userrefreshtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='myapp.user_login_info'),
        ),
    ]
