# Generated by Django 5.2 on 2026-02-05 20:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_user_workdetail_is_overtime_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='income',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='income',
            name='Income_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
