# Generated by Django 5.2 on 2025-12-24 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_userrefreshtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('work_date', models.DateField()),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
                ('work_place', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='User_WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=20)),
                ('minutes', models.PositiveIntegerField()),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.user_workday')),
            ],
        )
    ]
