# Generated by Django 5.2 on 2025-12-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_user_workday_user_workdetail_delete_user_work_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Work_Info',
        ),
    ]
