# Generated by Django 5.2 on 2026-02-12 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_expense_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='work_day',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_expense', to='myapp.user_workday'),
        ),
        migrations.CreateModel(
            name='WorkPlaceRate',
            fields=[
                ('rate_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_place', models.CharField(max_length=100)),
                ('base_hourly_wage', models.PositiveIntegerField(default=0)),
                ('overtime_hourly_wage', models.PositiveIntegerField(default=0)),
                ('meal_ot_hourly_wage', models.PositiveIntegerField(default=0)),
                ('special_hourly_wage', models.PositiveIntegerField(default=0)),
                ('overnight_hourly_wage', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='myapp.user_login_info')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Work_Pay',
        ),
        migrations.AddConstraint(
            model_name='workplacerate',
            constraint=models.UniqueConstraint(fields=('user', 'work_place'), name='uniq_user_work_place_rate'),
        ),
    ]
