# Generated by Django 5.2 on 2026-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_expense_work_day_workplacerate_delete_user_work_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplacerate',
            name='overnight_ot_hourly_wage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
