# Generated by Django 5.2 on 2026-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_workplacerate_overnight_ot_hourly_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplacerate',
            name='base_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplacerate',
            name='meal_ot_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplacerate',
            name='overnight_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplacerate',
            name='overnight_ot_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplacerate',
            name='overtime_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workplacerate',
            name='special_hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
