# Generated by Django 5.2 on 2026-02-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_workplacerate_base_hourly_wage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_workday',
            name='uniq_user_date_shift',
        ),
        migrations.AddConstraint(
            model_name='user_workday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved__isnull', True), ('is_approved', True), _connector='OR'), fields=('user_uuid', 'work_date', 'work_shift'), name='uniq_user_date_shift_not_rejected'),
        ),
    ]
