# Generated by Django 5.2 on 2026-06-24 20:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_workplacerate_early_hourly_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWorkPlace',
            fields=[
                ('admin_work_place_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_place', models.CharField(max_length=100)),
                ('base_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('overtime_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_ot_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('special_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('day_special_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('night_special_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('overnight_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('overnight_ot_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('early_hourly_wage', models.PositiveIntegerField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_places', to='myapp.admin_login_info')),
            ],
            options={
                'ordering': ['work_place'],
                'constraints': [models.UniqueConstraint(fields=('admin', 'work_place'), name='uniq_admin_work_place')],
            },
        ),
    ]
