# Generated by Django 4.2.30 on 2026-07-30 21:22

from django.db import migrations, models
import django.db.models.deletion
import myapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_encrypt_user_sensitive_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "schedule_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schedule_date", models.DateField(db_index=True, unique=True)),
                (
                    "original_file",
                    models.FileField(
                        upload_to=myapp.models.work_schedule_original_upload_to
                    ),
                ),
                ("original_file_name", models.CharField(max_length=255)),
                ("original_file_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_schedules",
                        to="myapp.admin_login_info",
                    ),
                ),
            ],
            options={
                "ordering": ["-schedule_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedulePreviewPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                (
                    "image",
                    models.FileField(
                        upload_to=myapp.models.work_schedule_preview_upload_to
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_pages",
                        to="myapp.workschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="workschedulepreviewpage",
            constraint=models.UniqueConstraint(
                fields=("schedule", "page_number"),
                name="uniq_work_schedule_preview_page",
            ),
        ),
    ]
