# Generated by Django 4.2.30 on 2026-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_user_workday_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workschedulepreviewpage",
            name="schedule",
        ),
        migrations.DeleteModel(
            name="WorkSchedule",
        ),
        migrations.DeleteModel(
            name="WorkSchedulePreviewPage",
        ),
    ]
