# Generated by Django 4.2.30 on 2026-08-12 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_remove_workschedulepreviewpage_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkSchedule",
            fields=[
                (
                    "schedule_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DAY", "주간"),
                            ("NIGHT", "야간"),
                            ("OFF", "휴무"),
                            ("TRAINING", "교육"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "work_place_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "work_place_detail",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_work_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_schedules",
                        to="myapp.adminworkplace",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employee_schedules",
                        to="myapp.admin_login_info",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_employee_schedules",
                        to="myapp.admin_login_info",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to="myapp.user_login_info",
                    ),
                ),
            ],
            options={
                "ordering": ["work_date", "user__user_name", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="employeeworkschedule",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "work_date",
                    "status",
                    "work_place_name",
                    "work_place_detail",
                ),
                name="uniq_employee_schedule_exact",
            ),
        ),
    ]
