// employeeData.js
export const employees = [
  {
    id: 1,
    employeeNumber: "A001",
    name: "김재선",
    status: "대기중",
    date: "2025-08-19",
    workTime: "09:00~18:00",
    location: "현장A",
    description: "전기 공사 작업",
    overtimeChecked: true,
    overtimeDuration: "18:00~20:00",
    lunchChecked: true,
    lunchDuration: "12:30~13:30",
    specialWorkChecked: false,
    specialWorkDuration: "",
  },
  {
    id: 2,
    employeeNumber: "A002",
    name: "박수빈",
    status: "승인",
    date: "2025-08-18",
    workTime: "08:30~17:30",
    location: "현장B",
    description: "용접 및 설치",
    overtimeChecked: false,
    overtimeDuration: "",
    lunchChecked: true,
    lunchDuration: "12:00~13:00",
    specialWorkChecked: true,
    specialWorkDuration: "17:30~19:30",
  },
  {
    id: 3,
    employeeNumber: "A003",
    name: "이준호",
    status: "대기중",
    date: "2025-08-17",
    workTime: "09:30~18:30",
    location: "현장C",
    description: "설비 점검",
    overtimeChecked: true,
    overtimeDuration: "18:30~20:30",
    lunchChecked: false,
    lunchDuration: "",
    specialWorkChecked: false,
    specialWorkDuration: "",
  },
  {
    id: 4,
    employeeNumber: "A004",
    name: "최민서",
    status: "거절",
    date: "2025-08-16",
    workTime: "09:00~18:00",
    location: "현장D",
    description: "자재 정리",
    overtimeChecked: false,
    overtimeDuration: "",
    lunchChecked: true,
    lunchDuration: "12:30~13:30",
    specialWorkChecked: true,
    specialWorkDuration: "18:00~19:00",
  },
  {
    id: 5,
    employeeNumber: "A005",
    name: "정하늘",
    status: "대기중",
    date: "2025-08-15",
    workTime: "08:00~17:00",
    location: "현장E",
    description: "장비 설치 및 테스트",
    overtimeChecked: false,
    overtimeDuration: "",
    lunchChecked: true,
    lunchDuration: "12:00~13:00",
    specialWorkChecked: false,
    specialWorkDuration: "",
  },
  {
    id: 6,
    employeeNumber: "A006",
    name: "홍길동",
    status: "승인",
    date: "2025-08-14",
    workTime: "09:00~18:00",
    location: "현장F",
    description: "보안 점검",
    overtimeChecked: true,
    overtimeDuration: "18:00~19:30",
    lunchChecked: true,
    lunchDuration: "12:30~13:30",
    specialWorkChecked: false,
    specialWorkDuration: "",
  },
  {
    id: 7,
    employeeNumber: "A007",
    name: "유진",
    status: "대기중",
    date: "2025-08-13",
    workTime: "08:30~17:30",
    location: "현장G",
    description: "현장 청소 및 정리",
    overtimeChecked: false,
    overtimeDuration: "",
    lunchChecked: true,
    lunchDuration: "12:00~13:00",
    specialWorkChecked: false,
    specialWorkDuration: "",
  },
];
